baseURL: "https://andypagdin.com"
title: Andy Pagdin - Software Engineer
paginate: 5
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "Andy Pagdin - Personal Website"
  ShowReadingTime: false
  defaultTheme: auto

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >

  socialIcons:
    - name: email
      url: "mailto:andyjpagdin@gmail.com"
    - name: linkedin
      url: "https://linkedin.com/in/andypagdin"
    - name: github
      url: "https://github.com/andypagdin"