baseURL: "https://example.com"
title: Andy Pagdin - Software Engineer
paginate: 5
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "Andy Pagdin - Personal Website"
  ShowReadingTime: false
  defaultTheme: dark
  assets:
    favicon: '<path / external url>'

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >

  socialIcons:
    - name: email
      url: "mailto:andyjpagdin@gmail.com"
    - name: linkedin
      url: "https://linkedin.com/in/andypagdin"
    - name: github
      url: "https://github.com/andypagdin"

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true